export const ipcChannels = {
  appGetInfo: 'app:get-info',
  systemGetPaths: 'system:get-paths',
  dbGetStatus: 'db:get-status',
  // ADR-029 M3: Ordinus conversation surface. Renderer (M4) consumes these.
  ordinusListConversations: 'ordinus:list-conversations',
  ordinusCreateConversation: 'ordinus:create-conversation',
  ordinusSendTurn: 'ordinus:send-turn',
  // ADR-029 M4.5: persisted transcript so the renderer can rehydrate after nav.
  ordinusListTurns: 'ordinus:list-turns',
  // Conversation ids with an in-flight turn. The "thinking" indicator is
  // ephemeral (no running-turn row in the DB), so the renderer queries this on
  // mount to rehydrate it after navigating back to Home, and keeps it live via
  // the turn_started / turn_settled action events.
  ordinusListRunningConversations: 'ordinus:list-running-conversations',
  // ADR-034: Stop button — cancel the in-flight turn of one conversation.
  ordinusCancelTurn: 'ordinus:cancel-turn',
  // ADR-035: reveal a file referenced by a transcript turn.
  ordinusRevealPath: 'ordinus:reveal-path',
  // ADR-029 M5: broadcast from main to renderer when an Ordinus action tool
  // completes (workboard plan ready, schedule created, workflow created).
  // One channel, discriminated payload — see OrdinusActionEventSchema.
  ordinusActionEvent: 'ordinus:action-event',
  // ADR-029 M6: confirmation gate. Renderer can list any pending entries on
  // mount (to rehydrate the panel after navigation) and submit a decision.
  ordinusListPendingConfirmations: 'ordinus:list-pending-confirmations',
  ordinusResolveConfirmation: 'ordinus:resolve-confirmation',
  // ADR-029: needs_input question panel. Renderer lists pending requests on
  // mount (rehydrate after restart), submits answers, or cancels.
  ordinusListPendingInputRequests: 'ordinus:list-pending-input-requests',
  ordinusAnswerInputRequest: 'ordinus:answer-input-request',
  ordinusCancelInputRequest: 'ordinus:cancel-input-request',
  // ADR-029 M7: persona + provider/model editing, plus the lifecycle hooks
  // (archive / freeze) the provider-change dialog and the frozen banner
  // rely on.
  ordinusGetSingleton: 'ordinus:get-singleton',
  ordinusUpdateSingleton: 'ordinus:update-singleton',
  ordinusArchiveConversation: 'ordinus:archive-conversation',
  ordinusUnarchiveConversation: 'ordinus:unarchive-conversation',
  ordinusDeleteConversation: 'ordinus:delete-conversation',
  ordinusUpdateConversationTitle: 'ordinus:update-conversation-title',
  ordinusSetConversationPinned: 'ordinus:set-conversation-pinned',
  // ADR-029 M8: memory panel CRUD. Shares the ordinus_memory table with the
  // memory_search / memory_write MCP tools.
  ordinusListMemory: 'ordinus:list-memory',
  ordinusWriteMemory: 'ordinus:write-memory',
  ordinusDeleteMemory: 'ordinus:delete-memory',
  setupGetStatus: 'setup:get-status',
  workspaceSelectFolder: 'workspace:select-folder',
  workspaceSaveConfig: 'workspace:save-config',
  workspaceUpdateSystemDefault: 'workspace:update-system-default',
  agentsList: 'agents:list',
  agentsListProfiles: 'agents:list-profiles',
  agentsDraftFromIntent: 'agents:draft-from-intent',
  agentsDraftFromProfile: 'agents:draft-from-profile',
  agentsDraftBlank: 'agents:draft-blank',
  agentsCreate: 'agents:create',
  agentsUpdateInstructions: 'agents:update-instructions',
  agentsUpdateSettings: 'agents:update-settings',
  agentsSetPinned: 'agents:set-pinned',
  agentsDelete: 'agents:delete',
  agentsListSkills: 'agents:list-skills',
  agentsGetSkill: 'agents:get-skill',
  agentsCreateSkill: 'agents:create-skill',
  agentsUpdateSkill: 'agents:update-skill',
  agentsDeleteSkill: 'agents:delete-skill',
  agentsListMemory: 'agents:list-memory',
  agentsAddMemory: 'agents:add-memory',
  agentsUpdateMemory: 'agents:update-memory',
  agentsDeactivateMemory: 'agents:deactivate-memory',
  agentsArchive: 'agents:archive',
  agentsUnarchive: 'agents:unarchive',
  agentsListReflection: 'agents:list-reflection',
  agentsAddExtraDirectory: 'agents:add-extra-directory',
  agentsRemoveExtraDirectory: 'agents:remove-extra-directory',
  agentsListExtraDirectories: 'agents:list-extra-directories',
  conversationsList: 'conversations:list',
  conversationsListAgentRoomSummaries: 'conversations:list-agent-room-summaries',
  conversationsGet: 'conversations:get',
  conversationsCreateDirect: 'conversations:create-direct',
  conversationsCreateManual: 'conversations:create-manual',
  conversationsGetOrCreateRoom: 'conversations:get-or-create-room',
  conversationsUpdateTitle: 'conversations:update-title',
  conversationsUpdateRoutingMode: 'conversations:update-routing-mode',
  conversationsSendTurn: 'conversations:send-turn',
  conversationsCancelTurn: 'conversations:cancel-turn',
  conversationsRevealPath: 'conversations:reveal-path',
  conversationsOpenFolder: 'conversations:open-folder',
  conversationsDeletePreview: 'conversations:delete-preview',
  conversationsDelete: 'conversations:delete',
  conversationsAnswerInputRequest: 'conversations:answer-input-request',
  conversationsCancelInputRequest: 'conversations:cancel-input-request',
  workboardList: 'workboard:list',
  workboardGenerateRequestPlan: 'workboard:generate-request-plan',
  workboardStartRequestPlan: 'workboard:start-request-plan',
  workboardListWorkspaceFolders: 'workboard:list-workspace-folders',
  workboardGeneratePlan: 'workboard:generate-plan',
  workboardStartRequest: 'workboard:start-request',
  workboardDirectStart: 'workboard:direct-start',
  workboardGenerateFollowUpPlan: 'workboard:generate-follow-up-plan',
  workboardStartFollowUp: 'workboard:start-follow-up',
  workboardListPendingPlans: 'workboard:list-pending-plans',
  workboardCreatePendingPlan: 'workboard:create-pending-plan',
  workboardDeletePendingPlan: 'workboard:delete-pending-plan',
  workboardCancelRun: 'workboard:cancel-run',
  workboardAnswerInputRequest: 'workboard:answer-input-request',
  workboardRevealPath: 'workboard:reveal-path',
  workboardSaveRunResult: 'workboard:save-run-result',
  workboardCheckPaths: 'workboard:check-paths',
  workboardArchiveRequest: 'workboard:archive-request',
  workboardUnarchiveRequest: 'workboard:unarchive-request',
  workflowDesignList: 'workflow:design-list',
  workflowDesignGet: 'workflow:design-get',
  workflowDesignCreate: 'workflow:design-create',
  workflowDesignUpdate: 'workflow:design-update',
  workflowDesignDelete: 'workflow:design-delete',
  workflowRun: 'workflow:run',
  observabilityListWorkboard: 'observability:list-workboard',
  observabilityListConversation: 'observability:list-conversation',
  observabilityGetTurnRun: 'observability:get-turn-run',
  observabilityListEvents: 'observability:list-events',
  observabilityGetDiagnostics: 'observability:get-diagnostics',
  observabilityRunChanged: 'observability:run-changed',
  runtimeGetProviders: 'runtime:get-providers',
  runtimeConnectProvider: 'runtime:connect-provider',
  runtimeDisconnectProvider: 'runtime:disconnect-provider',
  runtimeRefreshProvider: 'runtime:refresh-provider',
  connectorsList: 'connectors:list',
  connectorsConnect: 'connectors:connect',
  connectorsDisconnect: 'connectors:disconnect',
  filesRead: 'files:read',
  schedulesList: 'schedules:list',
  schedulesGet: 'schedules:get',
  schedulesCreate: 'schedules:create',
  schedulesUpdate: 'schedules:update',
  schedulesDelete: 'schedules:delete',
  schedulesSetEnabled: 'schedules:set-enabled',
  schedulesFireNow: 'schedules:fire-now',
  schedulesChanged: 'schedules:changed',
  onboardingGetStatus: 'onboarding:get-status',
  onboardingAdvanceFromWelcome: 'onboarding:advance-from-welcome',
  onboardingSelectProviders: 'onboarding:select-providers',
  onboardingConfirmWorkspace: 'onboarding:confirm-workspace',
  onboardingInstallProvider: 'onboarding:install-provider',
  onboardingInstallEvent: 'onboarding:install-event',
  onboardingResetProviders: 'onboarding:reset-providers',
  onboardingMarkProviderAuthed: 'onboarding:mark-provider-authed',
  onboardingComplete: 'onboarding:complete'
} as const
